### ISSUE TITLE
Nullable JsoupText

### ISSUE THREAD

**Issue by hram** [florent37/RxRetroJsoup#10]
How can I set field property as nullable.
Im my case on some web page in list of items one field in not requaired.
If I add this field I recieve not all available items.

**Comment by k0shk0sh** [comment]
Any news on this? As I'm seeing different behavior which I guess somehow related, 
I could find that some tag description is being passed to a different row, meaning the tag attached to the model belongs to the upper model. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hram** [comment]
I need help. How can I fix this?

**Comment by hram** [comment]
@florent37 can you please build new version with merged changes?

**Comment by florent37** [comment]
done ;) and published

2017-08-23 12:49 GMT+02:00 Evgeny Hramov <notifications@github.com>:

**Comment by hram** [comment]
@florent37 

Error:(92, 13) Failed to resolve: com.github.florent37:retrojsoup:1.0.4

maven-metadata.xml

`<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.github.florent37</groupId>
  <artifactId>retrojsoup</artifactId>
  <version>1.0.0</version>
  <versioning>
    <latest>1.0.0</latest>
    <release>1.0.0</release>
    <versions>
      <version>1.0.0</version>
    </versions>
    <lastUpdated>20170302080724</lastUpdated>
  </versioning>
</metadata>
`

**Comment by florent37** [comment]
I need to publish again ?

**Comment by hram** [comment]
no my last message was before #18 
now it works fine
