### ISSUE TITLE
RxJava 2

### ISSUE THREAD

**Issue by hram** [florent37/RxRetroJsoup#11]
RxJava 2 revision pattern is 'io.reactivex.rxjava2:rxjava:x.y.z'
In README.md is compile 'io.reactivex:rxjava:2.0.7'

**Comment by florent37** [comment]
fixed, thx

**Comment by hram** [comment]
I do not see fix
Fix can be io.reactivex.rxjava2:rxjava:2.0.7

**Comment by florent37** [comment]
can you check again ?

2017-05-04 7:51 GMT+02:00 Evgeny Hramov <notifications@github.com>:

**Comment by hram** [comment]
now is ok )
