### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by JamieYee** [florent37/RxRetroJsoup#15]
How to set up User-Agent      
thx

**Comment by hram** [comment]
you can setup http client
//optionally
.client(your_okhttp_client)

**Comment by JamieYee** [comment]
i know   okhttp setUser-Agent success   
Because okhttp need to set a url succeed ，RxRetroJsoup also need to set a url RxRetroJsoup print display did not succeed @hram

**Comment by JamieYee** [comment]
hi   What is a good way @hram 
![image](https://cloud.githubusercontent.com/assets/15099278/26611872/bc7a1204-45e3-11e7-9fcc-5266ddc5081a.png)

![image](https://cloud.githubusercontent.com/assets/15099278/26611884/ca07031e-45e3-11e7-9fbf-aa7ce3f7ddef.png)

![image](https://cloud.githubusercontent.com/assets/15099278/26611895/d8f6e2cc-45e3-11e7-950e-96870da84d6f.png)

**Comment by hram** [comment]
But you do not setup okhttp client in second example

**Comment by JamieYee** [comment]
sorry  
![image](https://cloud.githubusercontent.com/assets/15099278/26618580/6ccd9e4a-460d-11e7-9362-2c0f6dbfb61b.png)
  Wrote the same as before you set the User-Agent?
@hram

**Comment by hram** [comment]
Now you can set interceptor for okhttp and in this one set user agent

**Comment by JamieYee** [comment]
Did not understand, I set up in the RxRetroJsoup OKhttp client or not, whether you have done before the user agent，Is there a demo?
This question bothers me for a long time~

**Comment by JamieYee** [comment]
@hram  hlep me~

**Comment by hram** [comment]
you can create custom interceptor for okhttp

```
public class SomeInterceptor implements Interceptor {

    @Override
    public Response intercept(Interceptor.Chain chain) throws IOException {
        Response originalResponse = chain.proceed(chain.request());
        return originalResponse.newBuilder().header("Accept-Language", "some_header_parametr").build();
    }
}

```


and add this one to okkhttp

`OkHttpClient.Builder builder = new OkHttpClient.Builder().addNetworkInterceptor(new SomeInterceptor());`

**Comment by JamieYee** [comment]
activity is it written like this?
![image](https://cloud.githubusercontent.com/assets/15099278/26622343/ae171854-461c-11e7-8e9b-183eb8cbd94a.png)

@hram

**Comment by hram** [comment]
@yishangfei 
![client](https://cloud.githubusercontent.com/assets/2150637/26622891/9595f57a-45f4-11e7-9569-fb1199c32952.PNG)

**Comment by JamieYee** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/26624186/b327bf46-4622-11e7-93d8-b433e7aa24c1.png)
![image](https://cloud.githubusercontent.com/assets/15099278/26624198/bd8a9738-4622-11e7-9941-7b7db5b688ff.png)
Or do not have access to the computer version of the link ~  OMG

**Comment by hram** [comment]
@yishangfei with test https://stackoverflow.com/a/27840834

**Comment by JamieYee** [comment]
you konw okhttp set cookie？
