### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by hram** [florent37/RxRetroJsoup#6]
public class TrendingRetroJsoup implements Trending {
  private final RxJsoup rxJsoup;

  public TrendingRetroJsoup(String url, Boolean exceptionIfNotFound) {
    this.rxJsoup = new RxJsoup(url, exceptionIfNotFound);
  }

Error:(15, 20) error: constructor RxJsoup in class RxJsoup cannot be applied to given types;
required: String,boolean,OkHttpClient
found: String,Boolean
reason: actual and formal argument lists differ in length

    compile 'com.github.florent37:retrojsoup:1.0.2'
    compile 'com.github.florent37:rxjsoup:1.0.2'
    compile 'org.jsoup:jsoup:1.10.2'
    compile 'io.reactivex:rxjava:1.2.7'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    annotationProcessor 'com.github.florent37:retrojsoup-compiler:1.0.0'

**Comment by florent37** [comment]
did you update the 3 dependencies ?

2017-03-05 18:11 GMT+01:00 Evgeny Hramov <notifications@github.com>:

**Comment by hram** [comment]
no I updated dependencies 
list of dependencies  in issue

**Comment by hram** [comment]
I updated this 2:
compile 'com.github.florent37:retrojsoup:1.0.2'
compile 'com.github.florent37:rxjsoup:1.0.2'

What the third one?

**Comment by florent37** [comment]
The third is the retrojsoup compiler

**Comment by florent37** [comment]
try now, should be fixed (was a bintray upload error)

**Comment by florent37** [comment]
```annotationProcessor 'com.github.florent37:retrojsoup-compiler:1.0.2'```

**Comment by hram** [comment]
compile 'com.github.florent37:retrojsoup:1.0.2'
compile 'com.github.florent37:rxjsoup:1.0.2'
annotationProcessor 'com.github.florent37:retrojsoup-compiler:1.0.2'

error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.github.florent37.autoasync.processor.RetroJsoupProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/squareup/javapoet/TypeName
