### ISSUE TITLE
How to get value

### ISSUE THREAD

**Issue by hram** [florent37/RxRetroJsoup#7]
How can I get value "498"
Dom model on screenshot
![498](https://cloud.githubusercontent.com/assets/2150637/23591438/8671d0f0-0201-11e7-8c96-0eba82cc35cf.PNG)

**Comment by florent37** [comment]
please look at the jsoup syntax :
https://jsoup.org/cookbook/extracting-data/selector-syntax

2017-03-05 22:12 GMT+01:00 Evgeny Hramov <notifications@github.com>:
